name: Integration test
on: [push]
jobs:
  test-integration-stable:
    runs-on: ubuntu-latest
    services:
      chain1:
        image: informaldev/chain_a
        ports:
          - 26656:26656
          - 26657:26657
      chain2:
        image: informaldev/chain_b
        ports:
          - 26556:26656
          - 26557:26657
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p relayer
      - name: Set up relayer
        run: |
          TRUSTED_HEADER="$(curl -s http://localhost:26657/status)"
          HASH="$(echo "${TRUSTED_HEADER}" | jq -r .result.sync_info.latest_block_hash)"
          HEIGHT="$(echo "${TRUSTED_HEADER}" | jq -r .result.sync_info.latest_block_height)"
          target/debug/relayer -- -c relayer/relay/tests/config/fixtures/relayer_conf_example.toml light init -x "${HASH}" -h "${HEIGHT}" chain_A
          TRUSTED_HEADER="$(curl -s http://localhost:26557/status)"
          HASH="$(echo "${TRUSTED_HEADER}" | jq -r .result.sync_info.latest_block_hash)"
          export HEIGHT="$(echo "${TRUSTED_HEADER}" | jq -r .result.sync_info.latest_block_height)"
          target/debug/relayer -- -c relayer/relay/tests/config/fixtures/relayer_conf_example.toml light init -x "${HASH}" -h "${HEIGHT}" chain_B
      - name: Test env vars
        run: |
          echo "--"
          echo $HASH
          echo $HEIGHT
          echo "---"
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin relayer -- -c relayer/relay/tests/config/fixtures/relayer_conf_example.toml start --reset

